controllers/ClientesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Clientes;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Dompdf\Dompdf;
use yii\helpers\Html;
use yii\widgets\DetailView;

/**
 * ClientesController implements the CRUD actions for Clientes model.
 */
class ClientesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Clientes models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Clientes::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Clientes model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Clientes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Clientes();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cod]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Clientes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cod]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Clientes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Clientes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Clientes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Clientes::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionImprimir ($id){
        $cesion = Clientes::find($id); 
        $pdf = new Dompdf();
        // ob_start();
        // include_once 'datos.php';
        // $plantilla = ob_get_clean();
        $file_name = 'datos_cliente';
        
        $pdf->loadHTML('hola mundo');
        $pdf->render();
        return $pdf->stream($file_name. '.pdf');

    }
}

controllers/CompranController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Compran;
use app\models\Entradas;
use app\models\Clientes;
use app\models\Festivales;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Dompdf\Dompdf;


/**
 * CompranController implements the CRUD actions for Compran model.
 */
class CompranController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionNombre()
    {
        return $this->render('cambio_nombre');
    }

    /**
     * Lists all Compran models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Compran::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Compran model.
     * @param integer $cod_clientes
     * @param integer $cod_entradas
     * @param integer $cod_festivales
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($cod_clientes, $cod_entradas, $cod_festivales)
    {
        return $this->render('view', [
            'model' => $this->findModel($cod_clientes, $cod_entradas, $cod_festivales),
        ]);
    }

    /**
     * Creates a new Compran model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Compran();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'cod_clientes' => $model->cod_clientes, 'cod_entradas' => $model->cod_entradas, 'cod_festivales' => $model->cod_festivales]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Compran model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $cod_clientes
     * @param integer $cod_entradas
     * @param integer $cod_festivales
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($cod_clientes, $cod_entradas, $cod_festivales)
    {
        $model = $this->findModel($cod_clientes, $cod_entradas, $cod_festivales);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'cod_clientes' => $model->cod_clientes, 'cod_entradas' => $model->cod_entradas, 'cod_festivales' => $model->cod_festivales]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Compran model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $cod_clientes
     * @param integer $cod_entradas
     * @param integer $cod_festivales
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($cod_clientes, $cod_entradas, $cod_festivales)
    {
        $this->findModel($cod_clientes, $cod_entradas, $cod_festivales)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Compran model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $cod_clientes
     * @param integer $cod_entradas
     * @param integer $cod_festivales
     * @return Compran the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($cod_clientes, $cod_entradas, $cod_festivales)
    {
        if (($model = Compran::findOne(['cod_clientes' => $cod_clientes, 'cod_entradas' => $cod_entradas, 'cod_festivales' => $cod_festivales])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionImprimir($cod_clientes, $cod_entradas, $cod_festivales)
    {
        $cesion = Compran::find($cod_clientes); 
        $pdf = new Dompdf();
        // ob_start();
        // include_once 'datos.php';
        // $plantilla = ob_get_clean();
        $file_name = 'datos_cliente';
        
        $pdf->loadHTML('hola mundo');
        $pdf->render();
        return $pdf->stream($file_name. '.pdf');
    }

    public function actionCambioNombre($cod_clientes)
    {
        $model = $this->findModel($cod_clientes);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['cambio_nombre', 'cod_clientes' => $model->cod_clientes]);
        }

        return $this->render('cambio_nombre', [
            'model' => $model,
        ]);
    }
}

controllers/EntradasController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use app\models\Entradas;



/**
 * EntradasController implements the CRUD actions for Entradas model.
 */
class EntradasController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Entradas models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Entradas::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Entradas model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Entradas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Entradas();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cod]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Entradas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cod]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Entradas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
    public function actionEnt()
    {
        return $this->render('entradas');
    }

    /**
     * Finds the Entradas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Entradas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Entradas::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    public function actionTotal(){
        $numero = Yii::$app->db
                ->createCommand('SELECT COUNT(*) FROM entradas WHERE cod_festivales = 109;')
                ->queryScalar();
        
        $dataProvider = new SqlDataProvider([
            'sql' => 'SELECT COUNT(*) FROM entradas WHERE cod_festivales = 109;',
            'totalCount' => $numero,
            /*'pagination' =>[
                'pageSize' => 5,
                
            ]*/
        ]);
        
       return $this->render('entradas',[
            'total'=>$dataProvider,
            
        ]);


    }

}



controllers/FestivalesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Festivales;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * FestivalesController implements the CRUD actions for Festivales model.
 */
class FestivalesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Festivales models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Festivales::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Festivales model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Festivales model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Festivales();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cod]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Festivales model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cod]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Festivales model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
    public function actionFests()
    {
        return $this->render('fests');
    }
    
    public function actionMedusa()
    {
        return $this->render('medusa');
    }
    
    public function actionArenal()
    {
        return $this->render('arenal');
    }
    
    public function actionRiverland()
    {
        return $this->render('riverland');
    }
    
    public function actionSunblast()
    {
        return $this->render('sunblast');
    }
    

    /**
     * Finds the Festivales model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Festivales the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Festivales::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php $this->registerCsrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->registerLinkTag(['rel' => 'icon', 'type' => 'image/png', 'href' => '@web/imagenes/logo.png']); ?>

        <?php $this->head() ?>
    </head>
    <body>
        <?php $this->beginBody() ?>

        <div class="wrap">
            <?php
            NavBar::begin([
                'brandLabel' => Html::img('@web/imagenes/logo.png', ['alt' => Yii::$app->name, 'style' => 'margin-top: -15px; width: 40px; heigth: 44px;']),
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top opc',
                    'style' => 'padding: 8px 8px;'
                ],
            ]);
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => [
                    ['label' => 'Inicio', 'url' => ['/site/index'], 'options' => ['class' => 'opc']],
                    ['label' => 'Festivales', 'url' => ['/festivales/fests'], 'options' => ['class' => 'opc']],
                    ['label' => 'Entradas', 
                        'items' => [
                            ['label' => 'Comrpar Entradas', 'url' => ['/entradas/ent'], 'linkOptions' => ['class' => 'redes']],
                            ['label' => 'Cambio de Nombre', 'url' => ['/compran/nombre'], 'linkOptions' => ['class' => 'redes']],
                        ], 'options' => ['class' => 'opc']],
                    ['label' => 'Condiciones', 'url' => ['/site/about'], 'options' => ['class' => 'opc']],
                    ['label' => 'Redes Sociales',
                        'items' => [
                            '<li>
                        <a class="redes" href="https://www.instagram.com/?hl=es" tabindex="-1" target="_blank">
                            Instagram
                            <i style="margin-left: 5px;" class="fab fa-instagram"></i>
                        </a>
                    </li>
                     <li>
                        <a class="redes" href="https://twitter.com/?lang=es" tabindex="-1" target="_blank">
                            Twitter
                            <i style="margin-left: 5px;" class="fab fa-twitter"></i>
                        </a>
                    </li>
                     <li>
                        <a class="redes" href="https://www.facebook.com/" tabindex="-1" target="_blank">
                            Facebook
                            <i style="margin-left: 5px;" class="fab fa-facebook"></i>
                        </a>
                    </li>
                    <li>
                        <a class="redes" href="https://www.facebook.com/" tabindex="-1" target="_blank">
                            Youtube
                            <i style="margin-left: 5px;" class="fab fa-youtube"></i>
                        </a>
                    </li>'
                    
                        ], 'options' => ['class' => 'opc']
                    ],
                    ['label' => 'Contacto', 'url' => ['/site/contact'], 'options' => ['class' => 'opc']],
                    ['label' => 'Registro', 'url' => ['/clientes/create'], 'options' => ['class' => 'opc']],
                ],
            ]);
            NavBar::end();
            ?>
                <div class="container">
                    <?=
                    Breadcrumbs::widget([
                        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                    ])
                    ?>
                    <?= Alert::widget() ?>
                    <?= $content ?>
                </div>
        </div>

        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <span class="textfooter text-uppercase">&copy; <?=Yii::$app->name?> | </span>  
                        <?= Html::a('Condiciones | ', ['site/about']) ?> 
                        <?= Html::a('Contacto | ', ['site/contact']) ?> 
                        <a><?= Yii::powered() ?></a>
                    </div>
                </div>

            </div>
        </footer>

        <?php $this->endBody() ?>
        <script src="https://kit.fontawesome.com/a75ed5c33d.js" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

    </body>
</html>
<?php $this->endPage() ?>