models/Entradas.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "entradas".
 *
 * @property int $cod
 * @property int|null $numero_entrada
 * @property int|null $cod_festivales
 *
 * @property Compran[] $comprans
 * @property Clientes[] $codClientes
 * @property Festivales[] $codFestivales
 * @property Festivales $codFestivales0
 */
class Entradas extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'entradas';
    }
    
   

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['cod'], 'required'],
            [['cod', 'numero_entrada', 'cod_festivales'], 'integer'],
            [['cod'], 'unique'],
            [['cod_festivales'], 'exist', 'skipOnError' => true, 'targetClass' => Festivales::className(), 'targetAttribute' => ['cod_festivales' => 'cod']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'cod' => 'Cod',
            'numero_entrada' => 'Numero Entrada',
            'cod_festivales' => 'Cod Festivales',
        ];
    }

    /**
     * Gets query for [[Comprans]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getComprans()
    {
        return $this->hasMany(Compran::className(), ['cod_entradas' => 'cod']);
    }

    /**
     * Gets query for [[CodClientes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCodClientes()
    {
        return $this->hasMany(Clientes::className(), ['cod' => 'cod_clientes'])->viaTable('compran', ['cod_entradas' => 'cod']);
    }

    /**
     * Gets query for [[CodFestivales]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCodFestivales()
    {
        return $this->hasMany(Festivales::className(), ['cod' => 'cod_festivales'])->viaTable('compran', ['cod_entradas' => 'cod']);
    }

    /**
     * Gets query for [[CodFestivales0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCodFestivales0()
    {
        return $this->hasOne(Festivales::className(), ['cod' => 'cod_festivales']);
    }
}

controllers/CompranController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Compran;
use app\models\Entradas;
use app\models\Clientes;
use app\models\Festivales;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Dompdf\Dompdf;


/**
 * CompranController implements the CRUD actions for Compran model.
 */
class CompranController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionNombre()
    {
        return $this->render('cambio_nombre');
    }

    /**
     * Lists all Compran models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Compran::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Compran model.
     * @param integer $cod_clientes
     * @param integer $cod_entradas
     * @param integer $cod_festivales
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($cod_clientes, $cod_entradas, $cod_festivales)
    {
        return $this->render('view', [
            'model' => $this->findModel($cod_clientes, $cod_entradas, $cod_festivales),
        ]);
    }

    /**
     * Creates a new Compran model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Compran();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'cod_clientes' => $model->cod_clientes, 'cod_entradas' => $model->cod_entradas, 'cod_festivales' => $model->cod_festivales]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Compran model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $cod_clientes
     * @param integer $cod_entradas
     * @param integer $cod_festivales
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($cod_clientes, $cod_entradas, $cod_festivales)
    {
        $model = $this->findModel($cod_clientes, $cod_entradas, $cod_festivales);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'cod_clientes' => $model->cod_clientes, 'cod_entradas' => $model->cod_entradas, 'cod_festivales' => $model->cod_festivales]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Compran model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $cod_clientes
     * @param integer $cod_entradas
     * @param integer $cod_festivales
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($cod_clientes, $cod_entradas, $cod_festivales)
    {
        $this->findModel($cod_clientes, $cod_entradas, $cod_festivales)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Compran model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $cod_clientes
     * @param integer $cod_entradas
     * @param integer $cod_festivales
     * @return Compran the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($cod_clientes, $cod_entradas, $cod_festivales)
    {
        if (($model = Compran::findOne(['cod_clientes' => $cod_clientes, 'cod_entradas' => $cod_entradas, 'cod_festivales' => $cod_festivales])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionImprimir($cod_clientes, $cod_entradas, $cod_festivales)
    {
        $cesion = Compran::find($cod_clientes); 
        $pdf = new Dompdf();
        // ob_start();
        // include_once 'datos.php';
        // $plantilla = ob_get_clean();
        $file_name = 'datos_cliente';
        
        $pdf->loadHTML('hola mundo');
        $pdf->render();
        return $pdf->stream($file_name. '.pdf');
    }

    public function actionCambioNombre($cod_clientes)
    {
        $model = $this->findModel($cod_clientes);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['cambio_nombre', 'cod_clientes' => $model->cod_clientes]);
        }

        return $this->render('cambio_nombre', [
            'model' => $model,
        ]);
    }
}

controllers/EntradasController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use app\models\Entradas;



/**
 * EntradasController implements the CRUD actions for Entradas model.
 */
class EntradasController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Entradas models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Entradas::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Entradas model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Entradas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Entradas();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cod]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Entradas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cod]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Entradas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
    public function actionEnt()
    {
        return $this->render('entradas');
    }

    /**
     * Finds the Entradas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Entradas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Entradas::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    public function actionTotal(){
        $numero = Yii::$app->db
                ->createCommand('SELECT COUNT(*) FROM entradas WHERE cod_festivales = 109;')
                ->queryScalar();
        
        $dataProvider = new SqlDataProvider([
            'sql' => 'SELECT COUNT(*) FROM entradas WHERE cod_festivales = 109;',
            'totalCount' => $numero,
            /*'pagination' =>[
                'pageSize' => 5,
                
            ]*/
        ]);
        
       return $this->render('entradas',[
            'total'=>$dataProvider,
            
        ]);


    }

}



views/entradas/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Entradas */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="entradas-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'cod')->textInput() ?>

    <?= $form->field($model, 'numero_entrada')->textInput() ?>

    <?= $form->field($model, 'cod_festivales')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/entradas/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Entradas */

$this->title = 'Create Entradas';
$this->params['breadcrumbs'][] = ['label' => 'Entradas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="entradas-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/entradas/entradas.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;


$this->title = 'Entradas';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-entradas">
    <div class="col-md-12">
        <div class="col-sm-5 text-center bordes bg-imagen">
            <div class="thumbnail">
                <div class="caption">
                    <h3>Consulta para sacar nombre</h3>
                    <p>Total</p>
                    <div>
                        <?= Html::a('Comprar', ['/compran/create'], ['class' => 'btn btn-warning']) ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2 mt"></div>
        <div class="col-sm-5 text-center bordes bg-imagen">
            <div class="thumbnail">
                <div class="caption">
                    <h3>Consulta para sacar nombre</h3>
                    <p>Consulta para E.Restantes/E.Totales</p>
                    <div>
                        <?= Html::a('Comprar', ['/compran/create'], ['class' => 'btn btn-warning']) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-12 mt">
        <div class="col-sm-5 text-center bordes bg-imagen">
            <div class="thumbnail">
                <div class="caption">
                    <h3>Consulta para sacar nombre</h3>
                    <p>Consulta para E.Restantes/E.Totales</p>
                    <div>
                        <?= Html::a('Comprar', ['/compran/create'], ['class' => 'btn btn-warning']) ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2 mt"></div>
        <div class="col-sm-5 text-center bordes bg-imagen">
            <div class="thumbnail">
                <div class="caption">
                    <h3>Consulta para sacar nombre</h3>
                    <p>Consulta para E.Restantes/E.Totales</p>
                    <div>
                        <?= Html::a('Comprar', ['/compran/create'], ['class' => 'btn btn-warning']) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


views/entradas/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Entradas';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="entradas-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Entradas', ['create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'cod',
            'numero_entrada',
            'cod_festivales',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/entradas/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Entradas */

$this->title = 'Update Entradas: ' . $model->cod;
$this->params['breadcrumbs'][] = ['label' => 'Entradas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->cod, 'url' => ['view', 'id' => $model->cod]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="entradas-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/entradas/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Entradas */

$this->title = $model->cod;
$this->params['breadcrumbs'][] = ['label' => 'Entradas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="entradas-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->cod], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->cod], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'cod',
            'numero_entrada',
            'cod_festivales',
        ],
    ]) ?>

</div>