models/Festivales.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "festivales".
 *
 * @property int $cod
 * @property string|null $nombre
 * @property string|null $fecha_inicio
 * @property string|null $fecha_fin
 *
 * @property Compran[] $comprans
 * @property Clientes[] $codClientes
 * @property Entradas[] $codEntradas
 * @property Conciertos[] $conciertos
 * @property Entradas[] $entradas
 */
class Festivales extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'festivales';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['fecha_inicio', 'fecha_fin'], 'safe'],
            [['nombre'], 'string', 'max' => 25],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'cod' => 'Cod',
            'nombre' => 'Nombre del Festival',
            'fecha_inicio' => 'Fecha Inicio',
            'fecha_fin' => 'Fecha Fin',
        ];
    }

    /**
     * Gets query for [[Comprans]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getComprans()
    {
        return $this->hasMany(Compran::className(), ['cod_festivales' => 'cod']);
    }

    /**
     * Gets query for [[CodClientes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCodClientes()
    {
        return $this->hasMany(Clientes::className(), ['cod' => 'cod_clientes'])->viaTable('compran', ['cod_festivales' => 'cod']);
    }

    /**
     * Gets query for [[CodEntradas]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCodEntradas()
    {
        return $this->hasMany(Entradas::className(), ['cod' => 'cod_entradas'])->viaTable('compran', ['cod_festivales' => 'cod']);
    }

    /**
     * Gets query for [[Conciertos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getConciertos()
    {
        return $this->hasMany(Conciertos::className(), ['cod_festivales' => 'cod']);
    }

    /**
     * Gets query for [[Entradas]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getEntradas()
    {
        return $this->hasMany(Entradas::className(), ['cod_festivales' => 'cod']);
    }
}

controllers/FestivalesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Festivales;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * FestivalesController implements the CRUD actions for Festivales model.
 */
class FestivalesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Festivales models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Festivales::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Festivales model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Festivales model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Festivales();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cod]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Festivales model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cod]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Festivales model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
    public function actionFests()
    {
        return $this->render('fests');
    }
    
    public function actionMedusa()
    {
        return $this->render('medusa');
    }
    
    public function actionArenal()
    {
        return $this->render('arenal');
    }
    
    public function actionRiverland()
    {
        return $this->render('riverland');
    }
    
    public function actionSunblast()
    {
        return $this->render('sunblast');
    }
    

    /**
     * Finds the Festivales model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Festivales the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Festivales::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/festivales/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Festivales */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="festivales-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'fecha_inicio')->textInput() ?>

    <?= $form->field($model, 'fecha_fin')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/festivales/arenal.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Compran */

$this->title = 'Arenal Sound';
$this->params['breadcrumbs'][] = ['label' => 'Festivales', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>


views/festivales/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Festivales */

$this->title = 'Create Festivales';
$this->params['breadcrumbs'][] = ['label' => 'Festivales', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="festivales-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/festivales/fests.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;

$this->title = 'Festivales';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-fests">
    <div class="col-md-12">
        <div class="col-sm-5 text-center bordes bg-imagen">
            <div class="thumbnail">
                <div class="caption">
                    <h3 class="text-uppercase">Medusa</h3>
                    <p>El Medusa Sunbeach Festival es un festival de música electrónica dirigido principalmente
                        hacia un público joven de 16 años hasta la sepultura. Se celebra desde 2014 cada año <strong>en
                            la playa de Cullera, municipio de Valencia, Comunidad Valenciana.</strong><p>
                    <div>
                        <?= Html::a('Más Información', ['/festivales/medusa'], ['class' => 'btn btn-warning']) ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2 mt"></div>
        <div class="col-sm-5 text-center bordes bg-imagen">
            <div class="thumbnail">
                <div class="caption">
                    <h3 class="text-uppercase">Arenal Sound</h3>
                    <p>El festival Arenal Sound es un festival de música independiente que <strong>se celebra en la playa El Arenal, 
                            en la localidad de Burriana</strong>, durante la primera semana de agosto desde 2010.</p>
                    <div>
                        <?= Html::a('Más Información', ['/festivales/arenal'], ['class' => 'btn btn-warning']) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-12 mt" >
        <div class="col-sm-5 text-center bordes bg-imagen">
            <div class="thumbnail ">
                <div class="caption">
                    <h3 class="text-uppercase">Riverland</h3>
                    <p>El festival Riverland es un festival de música independiente <strong>celebrado en la localidad de Arriondas 
                            (provincia de Asturias, España)</strong> e inaugurado la primera semana de agosto de 2019.</p>
                    <div>
                        <?= Html::a('Más Información', ['/festivales/riverland'], ['class' => 'btn btn-warning']) ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2 mt"></div>
        <div class="col-sm-5 text-center bordes bg-cuadrado">
            <div class="thumbnail">
                <div class="caption">
                    <h3 class="text-uppercase">Sunblast</h3>
                    <p>El mayor festival de Canarias celebrado en Costa Adeje</p>
                    <div>
                        <?= Html::a('Más Información', ['/festivales/sunblast'], ['class' => 'btn btn-warning']) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
		
    
</div>


views/festivales/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Festivales';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="festivales-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Festivales', ['create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'cod',
            'nombre',
            'fecha_inicio',
            'fecha_fin',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/festivales/medusa.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Compran */

$this->title = 'Medusa Festival';
$this->params['breadcrumbs'][] = ['label' => 'Festivales', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>


views/festivales/riverland.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Compran */

$this->title = 'Riverland Festival';
$this->params['breadcrumbs'][] = ['label' => 'Festivales', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>


views/festivales/sunblast.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Compran */

$this->title = 'Sunblast Festival';
$this->params['breadcrumbs'][] = ['label' => 'Festivales', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

views/festivales/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Festivales */

$this->title = 'Update Festivales: ' . $model->cod;
$this->params['breadcrumbs'][] = ['label' => 'Festivales', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->cod, 'url' => ['view', 'id' => $model->cod]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="festivales-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/festivales/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Festivales */

$this->title = $model->cod;
$this->params['breadcrumbs'][] = ['label' => 'Festivales', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="festivales-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->cod], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->cod], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'cod',
            'nombre',
            'fecha_inicio',
            'fecha_fin',
        ],
    ]) ?>

</div>